 version: 2

 build:
   os: ubuntu-24.04
   tools:
     python: latest
   jobs:
     # https://docs.readthedocs.io/page/guides/reproducible-b
     build:
       html:
         - zensical build
     post_build:
       - mkdir -p $READTHEDOCS_OUTPUT/html/
       - cp --recursive site/* $READTHEDOCS_OUTPUT/html/
python:
  install:
    - requirements: docs/requirements.txt # Make sure this path is correct
    - method: pip
      path: .