from src.pydantask.prompts.prompts import (
    PLANNER_SYS_PROMPT,
    CRITIC_SYS_PROMPT,
    RESEARCH_AGENT_SYS_PROMPT,
    # SUPERVISOR_SYS_PROMPT,
    SUPERVISOR_INPUT_PROMPT,
    PRODUCER_SYS_PROMPT,
    WORKER_AGENT_SYS_PROMPT,
    DYNAMIC_SUPERVISOR_SYS_PROMPT,
)

__all__ = [
    "PLANNER_SYS_PROMPT",
    "CRITIC_SYS_PROMPT",
    "RESEARCH_AGENT_SYS_PROMPT",
    # "SUPERVISOR_SYS_PROMPT",
    "SUPERVISOR_INPUT_PROMPT",
    "PRODUCER_SYS_PROMPT",
    "WORKER_AGENT_SYS_PROMPT",
    "DYNAMIC_SUPERVISOR_SYS_PROMPT",
]
